import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://automationexercise.com/login');
  await page.locator('form').filter({ hasText: 'Login' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Login' }).getByPlaceholder('Email Address').fill('user_1761375575637@example.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Password123!');
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.locator('#header')).toContainText('Logout');
  await page.getByRole('link', { name: ' Products' }).click();
  await page.getByRole('textbox', { name: 'Search Product' }).click();
  await page.getByRole('textbox', { name: 'Search Product' }).fill('blue top');
  await page.getByRole('button', { name: '' }).click();
  await page.goto('https://automationexercise.com/products?search=blue%20top');
  await page.getByText('Add to cart').nth(1).click();
  await page.getByText('Add to cart').nth(1).click();
  await page.getByText('Add to cart').nth(1).click();
  await page.getByText('Add to cart').nth(1).click();
  await page.getByRole('link', { name: 'View Cart' }).click();
  await expect(page.locator('ol')).toContainText('Shopping Cart');
  await page.getByText('Proceed To Checkout').click();
  await page.goto('https://automationexercise.com/checkout');
  await expect(page.locator('ol')).toContainText('Checkout');
  await page.getByRole('link', { name: 'Place Order' }).click();
  await expect(page.locator('ol')).toContainText('Payment');
  await page.locator('input[name="name_on_card"]').click();
  await page.locator('input[name="name_on_card"]').fill('John Ali');
  await page.locator('input[name="card_number"]').click();
  await page.locator('input[name="card_number"]').fill('1098123409871234');
  await page.getByRole('textbox', { name: 'ex.' }).click();
  await page.getByRole('textbox', { name: 'ex.' }).fill('411');
  await page.getByRole('textbox', { name: 'MM' }).click();
  await page.getByRole('textbox', { name: 'MM' }).fill('12');
  await page.getByRole('textbox', { name: 'YYYY' }).click();
  await page.getByRole('textbox', { name: 'YYYY' }).fill('2027');
  await page.getByRole('button', { name: 'Pay and Confirm Order' }).click();
  await expect(page.locator('#form')).toContainText('Order Placed!');
  await expect(page.locator('#form')).toContainText('Congratulations! Your order has been confirmed!');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download Invoice' }).click();
  const download = await downloadPromise;
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download Invoice' }).click();
  const download = await downloadPromise;
});